services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=tennisdb'
      - 'MYSQL_PASSWORD=jackwagons'
      - 'MYSQL_ROOT_PASSWORD=jackwagonsroot'
      - 'MYSQL_USER=kalamalahala'
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql:/var/lib/mysql'
volumes:
    mysql:
